name: Validate libraries.json

on: pull_request

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Validate libraries.json
        run: |
          yarn validate:libraries
